# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{muck-shares}
  s.version = "3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Ball", "Joel Duffin"]
  s.date = %q{2010-10-05}
  s.description = %q{The share engine for the muck system.}
  s.email = %q{justin@tatemae.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/muck/shares_controller.rb",
     "app/helpers/muck_shares_helper.rb",
     "app/models/country.rb",
     "app/models/language.rb",
     "app/models/state.rb",
     "app/views/activity_templates/_share.html.erb",
     "app/views/shares/_form.html.erb",
     "app/views/shares/_share.html.erb",
     "app/views/shares/index.html.erb",
     "app/views/shares/new.html.erb",
     "config/locales/ar.yml",
     "config/locales/bg.yml",
     "config/locales/ca.yml",
     "config/locales/cs.yml",
     "config/locales/da.yml",
     "config/locales/de.yml",
     "config/locales/el.yml",
     "config/locales/en.yml",
     "config/locales/es.yml",
     "config/locales/et.yml",
     "config/locales/fa.yml",
     "config/locales/fi.yml",
     "config/locales/fr.yml",
     "config/locales/gl.yml",
     "config/locales/hi.yml",
     "config/locales/hr.yml",
     "config/locales/hu.yml",
     "config/locales/id.yml",
     "config/locales/it.yml",
     "config/locales/iw.yml",
     "config/locales/ja.yml",
     "config/locales/ko.yml",
     "config/locales/lt.yml",
     "config/locales/lv.yml",
     "config/locales/mt.yml",
     "config/locales/nl.yml",
     "config/locales/no.yml",
     "config/locales/pl.yml",
     "config/locales/pt-PT.yml",
     "config/locales/ro.yml",
     "config/locales/ru.yml",
     "config/locales/sk.yml",
     "config/locales/sl.yml",
     "config/locales/sq.yml",
     "config/locales/sr.yml",
     "config/locales/sv.yml",
     "config/locales/th.yml",
     "config/locales/tl.yml",
     "config/locales/tr.yml",
     "config/locales/uk.yml",
     "config/locales/vi.yml",
     "config/locales/zh-CN.yml",
     "config/locales/zh-TW.yml",
     "config/locales/zh.yml",
     "config/routes.rb",
     "db/migrate/20090803185323_create_shares.rb",
     "db/migrate/20090804184247_add_comment_count_to_shares.rb",
     "db/migrate/20090804231857_add_shares_uri_index.rb",
     "lib/muck_shares.rb",
     "lib/muck_shares/engine.rb",
     "lib/muck_shares/models/share.rb",
     "lib/muck_shares/models/sharer.rb",
     "lib/tasks/tasks.rb",
     "tasks/muck_shares_tasks.rake",
     "test/rails_root/.gitignore",
     "test/rails_root/.rake_tasks",
     "test/rails_root/config/global_config.yml",
     "test/rails_test/.gitignore",
     "test/rails_test/.rake_tasks",
     "test/rails_test/Gemfile",
     "test/rails_test/Rakefile",
     "test/rails_test/app/controllers/application_controller.rb",
     "test/rails_test/app/controllers/default_controller.rb",
     "test/rails_test/app/helpers/application_helper.rb",
     "test/rails_test/app/models/.keep",
     "test/rails_test/app/models/activity.rb",
     "test/rails_test/app/models/comment.rb",
     "test/rails_test/app/models/profile.rb",
     "test/rails_test/app/models/share.rb",
     "test/rails_test/app/models/user.rb",
     "test/rails_test/app/models/user_session.rb",
     "test/rails_test/app/views/default/index.html.erb",
     "test/rails_test/app/views/layouts/default.html.erb",
     "test/rails_test/config.ru",
     "test/rails_test/config/application.rb",
     "test/rails_test/config/boot.rb",
     "test/rails_test/config/database.yml",
     "test/rails_test/config/environment.rb",
     "test/rails_test/config/environments/development.rb",
     "test/rails_test/config/environments/production.rb",
     "test/rails_test/config/environments/test.rb",
     "test/rails_test/config/initializers/backtrace_silencers.rb",
     "test/rails_test/config/initializers/geokit_config.rb",
     "test/rails_test/config/initializers/inflections.rb",
     "test/rails_test/config/initializers/mime_types.rb",
     "test/rails_test/config/initializers/muck.rb",
     "test/rails_test/config/initializers/secret_token.rb",
     "test/rails_test/config/initializers/session_store.rb",
     "test/rails_test/config/routes.rb",
     "test/rails_test/features/shares.feature",
     "test/rails_test/features/step_definitions/common_steps.rb",
     "test/rails_test/features/step_definitions/share_steps.rb",
     "test/rails_test/features/step_definitions/web_steps.rb",
     "test/rails_test/features/support/custom_env.rb",
     "test/rails_test/features/support/env.rb",
     "test/rails_test/features/support/paths.rb",
     "test/rails_test/lib/tasks/cucumber.rake",
     "test/rails_test/spec/controllers/shares_controller_spec.rb",
     "test/rails_test/spec/models/share_spec.rb",
     "test/rails_test/spec/models/user_spec.rb",
     "test/rails_test/spec/spec_helper.rb",
     "test/rails_test/vendor/plugins/geokit-rails/.gitignore",
     "test/rails_test/vendor/plugins/geokit-rails/CHANGELOG.rdoc",
     "test/rails_test/vendor/plugins/geokit-rails/MIT-LICENSE",
     "test/rails_test/vendor/plugins/geokit-rails/README.markdown",
     "test/rails_test/vendor/plugins/geokit-rails/Rakefile",
     "test/rails_test/vendor/plugins/geokit-rails/about.yml",
     "test/rails_test/vendor/plugins/geokit-rails/assets/api_keys_template",
     "test/rails_test/vendor/plugins/geokit-rails/init.rb",
     "test/rails_test/vendor/plugins/geokit-rails/install.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/acts_as_mappable.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/adapters/abstract.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/adapters/mysql.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/adapters/postgresql.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/adapters/sqlserver.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/defaults.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/geocoder_control.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/ip_geocode_lookup.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/acts_as_mappable_test.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/boot.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/database.yml",
     "test/rails_test/vendor/plugins/geokit-rails/test/fixtures/companies.yml",
     "test/rails_test/vendor/plugins/geokit-rails/test/fixtures/custom_locations.yml",
     "test/rails_test/vendor/plugins/geokit-rails/test/fixtures/locations.yml",
     "test/rails_test/vendor/plugins/geokit-rails/test/fixtures/mock_addresses.yml",
     "test/rails_test/vendor/plugins/geokit-rails/test/fixtures/mock_families.yml",
     "test/rails_test/vendor/plugins/geokit-rails/test/fixtures/mock_houses.yml",
     "test/rails_test/vendor/plugins/geokit-rails/test/fixtures/mock_organizations.yml",
     "test/rails_test/vendor/plugins/geokit-rails/test/fixtures/mock_people.yml",
     "test/rails_test/vendor/plugins/geokit-rails/test/fixtures/stores.yml",
     "test/rails_test/vendor/plugins/geokit-rails/test/ip_geocode_lookup_test.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/company.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/custom_location.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/location.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/mock_address.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/mock_family.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/mock_house.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/mock_organization.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/mock_person.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/store.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/schema.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/tasks.rake",
     "test/rails_test/vendor/plugins/geokit-rails/test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/tatemae/muck_shares}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{muck-shares}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{The share engine for the muck system}
  s.test_files = [
    "test/rails_test/app/controllers/application_controller.rb",
     "test/rails_test/app/controllers/default_controller.rb",
     "test/rails_test/app/helpers/application_helper.rb",
     "test/rails_test/app/models/activity.rb",
     "test/rails_test/app/models/comment.rb",
     "test/rails_test/app/models/profile.rb",
     "test/rails_test/app/models/share.rb",
     "test/rails_test/app/models/user.rb",
     "test/rails_test/app/models/user_session.rb",
     "test/rails_test/config/application.rb",
     "test/rails_test/config/boot.rb",
     "test/rails_test/config/environment.rb",
     "test/rails_test/config/environments/development.rb",
     "test/rails_test/config/environments/production.rb",
     "test/rails_test/config/environments/test.rb",
     "test/rails_test/config/initializers/backtrace_silencers.rb",
     "test/rails_test/config/initializers/geokit_config.rb",
     "test/rails_test/config/initializers/inflections.rb",
     "test/rails_test/config/initializers/mime_types.rb",
     "test/rails_test/config/initializers/muck.rb",
     "test/rails_test/config/initializers/secret_token.rb",
     "test/rails_test/config/initializers/session_store.rb",
     "test/rails_test/config/routes.rb",
     "test/rails_test/features/step_definitions/common_steps.rb",
     "test/rails_test/features/step_definitions/share_steps.rb",
     "test/rails_test/features/step_definitions/web_steps.rb",
     "test/rails_test/features/support/custom_env.rb",
     "test/rails_test/features/support/env.rb",
     "test/rails_test/features/support/paths.rb",
     "test/rails_test/spec/controllers/shares_controller_spec.rb",
     "test/rails_test/spec/models/share_spec.rb",
     "test/rails_test/spec/models/user_spec.rb",
     "test/rails_test/spec/spec_helper.rb",
     "test/rails_test/vendor/plugins/geokit-rails/init.rb",
     "test/rails_test/vendor/plugins/geokit-rails/install.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/acts_as_mappable.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/adapters/abstract.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/adapters/mysql.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/adapters/postgresql.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/adapters/sqlserver.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/defaults.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/geocoder_control.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails/ip_geocode_lookup.rb",
     "test/rails_test/vendor/plugins/geokit-rails/lib/geokit-rails.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/acts_as_mappable_test.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/boot.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/ip_geocode_lookup_test.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/company.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/custom_location.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/location.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/mock_address.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/mock_family.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/mock_house.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/mock_organization.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/mock_person.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/models/store.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/schema.rb",
     "test/rails_test/vendor/plugins/geokit-rails/test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<muck-engine>, [">= 0"])
      s.add_runtime_dependency(%q<muck-users>, [">= 0"])
      s.add_runtime_dependency(%q<muck-activities>, [">= 0"])
      s.add_runtime_dependency(%q<muck-comments>, [">= 0"])
    else
      s.add_dependency(%q<muck-engine>, [">= 0"])
      s.add_dependency(%q<muck-users>, [">= 0"])
      s.add_dependency(%q<muck-activities>, [">= 0"])
      s.add_dependency(%q<muck-comments>, [">= 0"])
    end
  else
    s.add_dependency(%q<muck-engine>, [">= 0"])
    s.add_dependency(%q<muck-users>, [">= 0"])
    s.add_dependency(%q<muck-activities>, [">= 0"])
    s.add_dependency(%q<muck-comments>, [">= 0"])
  end
end

