# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{muck-shares}
  s.version = "3.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Ball", "Joel Duffin"]
  s.date = %q{2011-02-12}
  s.description = %q{The share engine for the muck system.}
  s.email = %q{justin@tatemae.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/muck/shares_controller.rb",
    "app/helpers/muck_shares_helper.rb",
    "app/views/activity_templates/_share.erb",
    "app/views/shares/_form.erb",
    "app/views/shares/_share.erb",
    "app/views/shares/destroy.js.erb",
    "app/views/shares/index.html.erb",
    "app/views/shares/new.html.erb",
    "config/locales/ar.yml",
    "config/locales/bg.yml",
    "config/locales/ca.yml",
    "config/locales/cs.yml",
    "config/locales/da.yml",
    "config/locales/de.yml",
    "config/locales/el.yml",
    "config/locales/en.yml",
    "config/locales/es.yml",
    "config/locales/et.yml",
    "config/locales/fa.yml",
    "config/locales/fi.yml",
    "config/locales/fr.yml",
    "config/locales/gl.yml",
    "config/locales/hi.yml",
    "config/locales/hr.yml",
    "config/locales/hu.yml",
    "config/locales/id.yml",
    "config/locales/it.yml",
    "config/locales/iw.yml",
    "config/locales/ja.yml",
    "config/locales/ko.yml",
    "config/locales/lt.yml",
    "config/locales/lv.yml",
    "config/locales/mt.yml",
    "config/locales/nl.yml",
    "config/locales/no.yml",
    "config/locales/pl.yml",
    "config/locales/pt-PT.yml",
    "config/locales/ro.yml",
    "config/locales/ru.yml",
    "config/locales/sk.yml",
    "config/locales/sl.yml",
    "config/locales/sq.yml",
    "config/locales/sr.yml",
    "config/locales/sv.yml",
    "config/locales/th.yml",
    "config/locales/tl.yml",
    "config/locales/tr.yml",
    "config/locales/uk.yml",
    "config/locales/vi.yml",
    "config/locales/zh-CN.yml",
    "config/locales/zh-TW.yml",
    "config/locales/zh.yml",
    "config/routes.rb",
    "db/migrate/20090803185323_create_shares.rb",
    "db/migrate/20090804184247_add_comment_count_to_shares.rb",
    "db/migrate/20090804231857_add_shares_uri_index.rb",
    "db/migrate/20101008234613_add_shared_by_type.rb",
    "lib/muck-shares.rb",
    "lib/muck-shares/engine.rb",
    "lib/muck-shares/models/share.rb",
    "lib/muck-shares/models/sharer.rb",
    "lib/tasks/muck_shares.rake",
    "muck-shares.gemspec"
  ]
  s.homepage = %q{http://github.com/tatemae/muckshares}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{The share engine for the muck system}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<muck-engine>, [">= 0"])
      s.add_runtime_dependency(%q<muck-users>, [">= 0"])
      s.add_runtime_dependency(%q<muck-activities>, [">= 0"])
      s.add_runtime_dependency(%q<muck-comments>, [">= 0"])
    else
      s.add_dependency(%q<muck-engine>, [">= 0"])
      s.add_dependency(%q<muck-users>, [">= 0"])
      s.add_dependency(%q<muck-activities>, [">= 0"])
      s.add_dependency(%q<muck-comments>, [">= 0"])
    end
  else
    s.add_dependency(%q<muck-engine>, [">= 0"])
    s.add_dependency(%q<muck-users>, [">= 0"])
    s.add_dependency(%q<muck-activities>, [">= 0"])
    s.add_dependency(%q<muck-comments>, [">= 0"])
  end
end

